### ISSUE TITLE
StdGen Fails Small Crush Test

### ISSUE THREAD

**Issue by idontgetoutmuch** [nkartashov/htestu#2]
For

```
runCrush crush = (\g -> runBatteryToResults nextStreamFromGen g crush ) `fmap` newStdGen
```

I get

```
./doc/examples/TestGen
[Fail,Fail,OK,OK,OK,Fail,Fail,OK,OK,OK,Fail,Fail,Fail,Fail,Fail]
```

Is this expected?

**Comment by nkartashov** [comment]
I had the same result. Pcg, splitmix and as far as I remember tf-random pass it.

**Comment by idontgetoutmuch** [comment]
Ah ok - I have now had chance to have a quick butcher's at L'Ecuyer and Simard (I haven't read all 200+ pages). It seems to me we should write up the results for `StdGen`, `Pcg`, `splitmix` and `tf-random`. I will close this and add a task to https://github.com/haskell/random/issues/31.

**Comment by cartazio** [comment]
Only split mix and pcg random pass big crush.  And only split mix has a split that passes big crush.  Though I need to dig into how we test that more
