### ISSUE TITLE
/Users/nikita_kartashov/Documents/Work/haskell/htestu/dist/build/lib/libprobdist.0.dylib referenced - why?

### ISSUE THREAD

**Issue by idontgetoutmuch** [nkartashov/htestu#3]
```
htestu $ stack exec ghci -- -Lcbits/testu/src/.libs -ltestu01
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
<command line>: user specified .o/.so/.DLL could not be loaded (dlopen(cbits/testu/src/.libs/libtestu01.dylib, 5): Library not loaded: /Users/nikita_kartashov/Documents/Work/haskell/htestu/dist/build/lib/libprobdist.0.dylib
  Referenced from: /Users/dom/Dropbox/Private/Libraries/htestu/cbits/testu/src/.libs/libtestu01.dylib
  Reason: image not found)
Whilst trying to load:  (dynamic) cbits/testu/src/.libs/libtestu01.dylib
Additional directories searched:   cbits/testu/src/.libs
```

Why is a file on your computer being referenced? How do I load and run e.g. `src/Test/HTestU.hs` in `ghci`?

**Comment by nkartashov** [comment]
The files in .deps and .libs are autogenerated and were committed by accident, after deleting them my next cabal build was successful. You can run your code in GHCi the following way:
`stack exec ghci -- -lHShtestu-0.1.0.0-FfHl6IdxHQV7NsHHHyJUcU-ghc7.10.2 -Ldist/build` where libHShtestu-0.1.0.0-FfHl6IdxHQV7NsHHHyJUcU-ghc7.10.2.{so, dylib, dll} is your compiled lib, lib can be compiled with cabal build. Does that work for you?

**Comment by idontgetoutmuch** [comment]
That works for me.
